from __future__ import annotations

DOWNLOAD_STATUS_PENDING = "pending"
DOWNLOAD_STATUS_RUNNING = "running"
DOWNLOAD_STATUS_RETRY_WAIT = "retry_wait"
DOWNLOAD_STATUS_SUCCESS = "success"
DOWNLOAD_STATUS_FAILED = "failed"
DOWNLOAD_STATUS_CANCELLED = "cancelled"
DOWNLOAD_STATUS_SKIPPED = "skipped"

DOWNLOAD_STATUS_ALL = {
    DOWNLOAD_STATUS_PENDING,
    DOWNLOAD_STATUS_RUNNING,
    DOWNLOAD_STATUS_RETRY_WAIT,
    DOWNLOAD_STATUS_SUCCESS,
    DOWNLOAD_STATUS_FAILED,
    DOWNLOAD_STATUS_CANCELLED,
    DOWNLOAD_STATUS_SKIPPED,
}

DOWNLOAD_STATUS_ACTIVE_DEDUP = {
    DOWNLOAD_STATUS_PENDING,
    DOWNLOAD_STATUS_RUNNING,
    DOWNLOAD_STATUS_RETRY_WAIT,
    DOWNLOAD_STATUS_SUCCESS,
}

DOWNLOAD_STATUS_RUNNABLE = {
    DOWNLOAD_STATUS_PENDING,
    DOWNLOAD_STATUS_RETRY_WAIT,
}

DOWNLOAD_STATUS_RETRYABLE = {
    DOWNLOAD_STATUS_FAILED,
    DOWNLOAD_STATUS_RETRY_WAIT,
    DOWNLOAD_STATUS_SKIPPED,
}
